### PR TITLE
Add AE and NO language files

### PR DESCRIPTION
**Pull request by bovirus**
Add AE and NO language files

### CODE REVIEW

**Comment by XECDesign** [comment]
Missing the changes to icons.qrc

**Comment by bovirus** [comment]
@@XECDesign

Could you please merge my pull request and edit you directly icons.qrc to add ae/no languages?
Thanks.

**Comment by XECDesign** [comment]
As a one off, sure.

In the future, please build and test all changes before submitting the pull request.

**Comment by XECDesign** [comment]
The correct ISO 639-1 code for Arabic is ar, rather than ae (which is ISO 3166-2 country code for UAE). Doing a test build with that fix now as well.

**Pull request merged**
