### PR TITLE
Update partclone.mk

### PR DESCRIPTION
**Pull request by procount**
Corrected download URL.
I'm sure this might have been mentioned before, but I couldn't find a reference.

### CODE REVIEW

**Comment by lurch** [comment]
> I'm sure this might have been mentioned before, but I couldn't find a reference.

Oh? https://github.com/raspberrypi/noobs/search?q=partclone&type=Issues&utf8=%E2%9C%93  :wink: 

I've not tried building NOOBS myself for a couple of years, so I've no idea if this is still a problem or if this PR fixes it!

**Comment by procount** [comment]
It could be that it has been fixed already, but I just did a fresh build of pinn and hit the same error so I thought I'd note it down before I forgot.

**Comment by procount** [comment]
This still looks like it will be an issue for any new developers building NOOBS for the first time.

**Comment by XECDesign** [comment]
No issue with the URL as is for me:
```
shift@serge-pc ~ $ wget http://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz
URL transformed to HTTPS due to an HSTS policy
--2018-02-23 16:15:56--  https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz/download [following]
--2018-02-23 16:15:57--  https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz/download
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz?r=&ts=1519402558&use_mirror=10gbps-io [following]
--2018-02-23 16:15:58--  https://downloads.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz?r=&ts=1519402558&use_mirror=10gbps-io
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://10gbps-io.dl.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz [following]
--2018-02-23 16:15:59--  https://10gbps-io.dl.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz
Resolving 10gbps-io.dl.sourceforge.net (10gbps-io.dl.sourceforge.net)... 185.152.64.70
Connecting to 10gbps-io.dl.sourceforge.net (10gbps-io.dl.sourceforge.net)|185.152.64.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1033606 (1009K) [application/x-gzip]
Saving to: ‘partclone-0.2.84.tar.gz’

partclone-0.2.84.tar.gz                              100%[=====================================================================================================================>]   1009K  2.07MB/s    in 0.5s    

2018-02-23 16:16:00 (2.07 MB/s) - ‘partclone-0.2.84.tar.gz’ saved [1033606/1033606]

shift@serge-pc ~ $ file partclone-0.2.84.tar.gz
partclone-0.2.84.tar.gz: gzip compressed data, last modified: Tue Oct 13 06:27:56 2015, from Unix
shift@serge-pc ~ $ tar xvf partclone-0.2.84.tar.gz  -O > /dev/null
partclone-0.2.84/
partclone-0.2.84/.gitattributes
partclone-0.2.84/.gitignore
...
```

**Comment by procount** [comment]
This is what I get when I do a `make partclone` with it as it is:
```
>>> partclone 0.2.84 Downloading
--2018-02-23 19:21:55--  http://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz [following]
--2018-02-23 19:22:03--  https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
ERROR: cannot verify sourceforge.net's certificate, issued by ‘/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA’:
  Unable to locally verify the issuer's authority.
To connect to sourceforge.net insecurely, use `--no-check-certificate'.
--2018-02-23 19:22:03--  http://sources.buildroot.net/partclone-0.2.84.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.27.167.48, 104.27.166.48, 2400:cb00:2048:1::681b:a730, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.27.167.48|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-23 19:22:04 ERROR 404: Not Found.
```
And when I modify it as this PR:
```
>>> partclone 0.2.84 Downloading
--2018-02-23 19:23:07--  http://downloads.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://netix.dl.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz [following]
--2018-02-23 19:23:07--  https://netix.dl.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz
Resolving netix.dl.sourceforge.net (netix.dl.sourceforge.net)... 87.121.121.2
Connecting to netix.dl.sourceforge.net (netix.dl.sourceforge.net)|87.121.121.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1033606 (1009K) [application/x-gzip]
Saving to: ‘/home/procount/noobs_test/buildroot/output/build/.partclone-0.2.84.tar.gz.a5ywA1/output’

100%[==================================================================================================================================================================>] 1,033,606   1.37MB/s   in 0.7s   

2018-02-23 19:23:08 (1.37 MB/s) - ‘/home/procount/noobs_test/buildroot/output/build/.partclone-0.2.84.tar.gz.a5ywA1/output’ saved [1033606/1033606]
```
I wonder if it is to do with which mirror sourceforge gives you?

I tried a direct wget as you did (but with a --no-check-certificate). The first time it failed. The second time it downloaded.

I know when I first started using Sourceforge for all the OS downloads, it took me a while to get the correct syntax that would work reliably.

**Comment by lurch** [comment]
> I wonder if it is to do with which mirror sourceforge gives you?

Maybe? Obviously when mirrors are involved it gets hard to consistently reproduce problems.

I see this in your output:
```
ERROR: cannot verify sourceforge.net's certificate, issued by ‘/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA’:
  Unable to locally verify the issuer's authority.
```
I wonder if maybe different versions of `wget` (or possibly some add-on package) have different sets of SSL certificates that they do or don't trust? :man_shrugging:  (ISTR that at one point this was causing all _sorts_ of problems for `rpi-update`, which IIRC moved from `wget` to `curl`)

FWIW, this is what I get on Ubuntu 14.04 (on ADSL in Cambridge, if that makes any difference)
```
$ wget "http://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz"
--2018-02-24 00:25:23--  http://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz [following]
--2018-02-24 00:25:24--  https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz/download [following]
--2018-02-24 00:25:24--  https://sourceforge.net/projects/partclone/files/source/partclone-0.2.84.tar.gz/download
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz?r=&ts=1519431925&use_mirror=netcologne [following]
--2018-02-24 00:25:25--  https://downloads.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz?r=&ts=1519431925&use_mirror=netcologne
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://netcologne.dl.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz [following]
--2018-02-24 00:25:26--  https://netcologne.dl.sourceforge.net/project/partclone/source/partclone-0.2.84.tar.gz
Resolving netcologne.dl.sourceforge.net (netcologne.dl.sourceforge.net)... 78.35.24.46, 2001:4dd0:1234:6::5f
Connecting to netcologne.dl.sourceforge.net (netcologne.dl.sourceforge.net)|78.35.24.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1033606 (1009K) [application/x-gzip]
Saving to: ‘partclone-0.2.84.tar.gz’

100%[======================================>] 1,033,606   1.70MB/s   in 0.6s   

2018-02-24 00:25:27 (1.70 MB/s) - ‘partclone-0.2.84.tar.gz’ saved [1033606/1033606]
```

**Comment by XECDesign** [comment]
@procount does the original URL still not work for you?

**Comment by procount** [comment]
9 times out of 10 it will fail for me. It's just not a reliable URL, I think it might depend on the mirror used (?) whereas the URL I propose always works for me.
(Sourceforge have been moving data centre recently and have had many problems. Don't know if that is related 🤷‍♂️ : )

**Comment by XECDesign** [comment]
On one hand, I don't know if the new URL will work for everybody else. On the other hand, if the new URL works for lurch, you and me, why not.... merged. Thanks.

**Pull request merged**
