### PR TITLE
Add Installation of OS Images from USB

### PR DESCRIPTION
**Pull request by robbi5**
Hi,

for various use cases like
- users with a small SD card
- sharing one usb pendrive in a classroom
- (re)installing on an raspberry pi compute module
- ...?

it would be great to use os images stored on an USB storage device.
This PR mounts the first partition of an FAT formatted USB drive (`/dev/sda1`) if available and looks for additional os images in the `os` folder on it.

I've seen other people looking for something like this too: #164 and #213

### CODE REVIEW

**Comment by robbi5** [comment]
Hi,
thanks for the buildroot update :+1: 
A fresh version of the changes on top of NOOBS v1.3.12 is in [headissue:usb-os-install-pi2](https://github.com/headissue/noobs/tree/usb-os-install-pi2).
Should we close this PR and open a new one?

**Comment by lurch** [comment]
It's up to you - you can either close this PR and open a new one; or you can do an interactive git rebase to push your changes into this PR (your headissue:usb-os-install branch).

I can't make any promises yet when / if this PR will get merged into mainline though.

**Comment by ghollingworth** [comment]
Might try merging this into Slice NOOBS since it would be useful to be
able to update from a USB stick

Gordon

**Comment by procount** [comment]
Is it necessary to include the line "# CONFIG_WLAN is not set" in both the kernel config files? I think removing this line from each will not affect the build, but will allow easier integration with #243 - the wifi addition. Please correct me if I am wrong.

**Comment by lurch** [comment]
IIRC if you start manually taking out the `# XXX is not set`, then when you build the kernel it assumes that this is a new not-seen-before setting, and then asks you whether it should be enabled or not. Which can then cause problems with the buildroot process, as it doesn't expect the build process to require interactive intervention.

The contents of the kernel config files are determined automatically by the kernel's `defconfig` Makefile target (see #243 for a discussion of how this has been integrated into the dual-kernel setup of NOOBS).

**Comment by procount** [comment]
I originally thought that "# CONFIG_WLAN is not set" was just a comment, but it seems it actively disable the wifi configuration. When integrated with #243 all the wifi functionaltiy stopped working and removing this line resolves the issue. Interestingly, there is no CONFIG_WLAN setting in the kermel config files for #243, which I guess is why there was no merge conflict to flag up this issue. Perhaps the issue is that #243 should have "CONFIG_WLAN=y" ???

**Comment by procount** [comment]
Probably this is just my integration issue. Does "# CONFIG_WLAN is not set" get removed and replaced by its sub-menu options when it is selected? In which case I need to take care when merging the kernel-recovery files that you get one option or the other but not both, which a simple merge will not identify.

**Comment by lurch** [comment]
This is all very much AIUI (I might be wrong), but I believe the 'defconfig' is automatically created as the 'minimal set of config options' needed for a specific kernel configuration. As such, `CONFIG_RT2X00=y` in e.g. `buildroot/kernelconfig-recovery.armv6` *implies* `CONFIG_WLAN=y` and so there's no need to explicitly include the CONFIG_WLAN option. (I believe when you 'apply' the defconfig, it automatically creates the full every-option-included .config file)

> When integrated with #243 all the wifi functionaltiy stopped working and removing this line resolves the issue.

I guess the lesson here is that you can't simply merge 'defconfig' files...? Perhaps there is a way to do what you want 'automatically' but I'm afraid I dunno what that is.

Pinging @popcornmix as he seems to be very familiar with manipulating the defconfig files for https://github.com/raspberrypi/linux

**Comment by procount** [comment]
Maybe it is necessary to create the full .config file for each defconfig option, merge and resolve the full .config files, then create a defconfig file from that?

**Comment by lurch** [comment]
> Maybe it is necessary to create the full .config file for each defconfig option, merge and resolve the full .config files, then create a defconfig file from that?

Sounds plausible :)

**Comment by procount** [comment]
This is now supported in NOOBS 2.4, so I think this can be closed.

**Comment by XECDesign** [comment]
Thanks

**Pull request closed without merging**
