### PR TITLE
Make timeout configurable in config.h

### PR DESCRIPTION
**Pull request by fonic**
I think the timeout is something that should be configurable. Here's the tiny patch for it.

EDIT:
Sorry for the translation file being part of the pull request. I'm new to GitHub, still tricks me from time to time. Can be safely merged as the translation file is the same as in my other pull request for the translation.

### CODE REVIEW

**Comment by XECDesign** [comment]
Sorry, we won't be adding this.

**Comment by fonic** [comment]
Why not? If the reason is the translation files, I can create a new, clean pull request.

**Comment by XECDesign** [comment]
Alright, it's optional and harmless, so may as well add it. Send a clean PR.

**Comment by fonic** [comment]
Will do!

**Pull request closed without merging**
