### PR TITLE
Update Japanese translation.

### PR DESCRIPTION
**Pull request by Akkiesoft**

### CODE REVIEW

**Comment by soramugi** [comment]
:eyes:

**Comment by lurch** [comment]
Sorry, been very busy with lots of other stuff https://github.com/raspberrypi/noobs/releases and I'm afraid adding / updating (& testing) new and modified [translations](https://github.com/raspberrypi/noobs/labels/translation) hasn't been very high on my list of priorities.
Don't know yet when I'm likely to be able to get round to it either :-/

**Comment by Akkiesoft** [comment]
I saw #364 and I have started to translate translation_ja.ts again.
First, I have been resolved conflict.
Next, I will translate new words updated after 2014.

**Comment by bovirus** [comment]
@ Akkiesoft
If you post your current translation I can update with latets strings and now you can works without conflict

**Comment by XECDesign** [comment]
See #373
Thank you

**Pull request closed without merging**
