### PR TITLE
Added slovak translation

### PR DESCRIPTION
**Pull request by prescott66**
Created slovak translation(100%) based on latest sources.

### CODE REVIEW

**Comment by XECDesign** [comment]
Could you please add the relevant recovery.pro and icons.qrc changes?

**Comment by prescott66** [comment]
I hope it is fine now...if not, correct me please.

**Comment by XECDesign** [comment]
Thank you. Will let you know after a test build.

**Comment by XECDesign** [comment]
Seems okay. Thanks

**Pull request merged**
