### PR TITLE
Change Recovery Splash Screen

### PR DESCRIPTION
**Pull request by duckida**
I removed the old wallpaper and replaced it with my new one to solve #608!

### CODE REVIEW

**Comment by lurch** [comment]
`recovery/Screen Shot 2020-11-16 at 12.58.27 PM.png` ??? I think something might have gone wrong with your PR :laughing:

**Comment by duckida** [comment]
> `recovery/Screen Shot 2020-11-16 at 12.58.27 PM.png` ??? I think something might have gone wrong with your PR 😆

Fixed it, @lurch

**Comment by lurch** [comment]
Your new wallpaper is 1026x688, which means it probably wouldn't look very good when viewed at 640x480 ? (don't forget that NOOBS also supports composite-video output)

**Comment by lurch** [comment]
Looks like this branch is no longer relevant to the original PR. Should it be closed @duckida ?

**Pull request closed without merging**
