### PR TITLE
Galician translation

### PR DESCRIPTION
**Pull request by alexandregz**
Galician language (ISO code gl)

### CODE REVIEW

**Comment by XECDesign** [comment]
Thank you. Will merge before next NOOBS release.

**Comment by XECDesign** [comment]
Looks like we forgot to add it to recovery.pro, so it didn't quite make it into NOOBS 3.3.

**Comment by lurch** [comment]
Looking at https://github.com/raspberrypi/noobs#addingupdating-translations I guess `icons.qrc` should have been updated too.

**Comment by procount** [comment]
Is Galician another Spanish dialect?
I think GL the ISO country code for greenland.....

**Comment by XECDesign** [comment]
Yup, you're right.

**Comment by XECDesign** [comment]
I'll need to read qt's localisation documentation again later, since I've forgotten a lot of how it, but at a glance, it looks like  `gl` may be right after all. We're specifying the language, not the country. The language is a ISO 639 code, which is indeed `gl` for Galician. `GL` is the ISO 3166-1 alpha-2 country code for Greenland. Qt seems to take `language[_script][_country][.codeset][@modifier]` in the QLocale constructor. So, I _think_ we're okay, but will have to double check when I have time.

**Comment by lurch** [comment]
https://en.wikipedia.org/wiki/Galician_language confirms that `gl` is the ISO 639-1 language code for Galician. Note that language-codes and country-codes are different, and frequently overlap and/or clash :upside_down_face:

**Comment by XECDesign** [comment]
I bet we have the same set of wikipedia tabs open.

**Comment by procount** [comment]
Yep, it's been a while since I last looked too, so it's probably ok.

**Comment by alexandregz** [comment]
Hi, galician is a language, not a dialect 

It's very close to Portuguese, in fact Galician is the origin of Portuguese 😄

**Pull request merged**
