### PR TITLE
Fix for (NOOBS installer does not recognize HID (Keyboard/Mouse) #257)

### PR DESCRIPTION
**Pull request by adamstraube**
https://github.com/raspberrypi/noobs/issues/257

I have added extra HID drivers to allow for some non standard keyboards to be used in Noobs. Basically if a keyboard worked in Raspbian, OpenElec etc... but not in Noobs then this should solve the issue.

### CODE REVIEW

**Comment by voltagex** [comment]
Any updates on this?

**Comment by NicoHood** [comment]
I think this change was already made.
https://github.com/raspberrypi/noobs/commit/6894dd251e5cf86c06b3a778a53a8944c3817208#diff-1c8f157a08c2f2c03833567482a7c354

**Comment by voltagex** [comment]
Yep, this can be closed.

**Comment by Ruffio** [comment]
can this be closed? @voltagex says that the change has allready been made...

**Pull request closed without merging**
