### PR TITLE
Added Spanish translation.

### PR DESCRIPTION
**Pull request by amorellgarcia**

### CODE REVIEW

**Comment by xinjia95** [comment]
Why not have even included this PR?

**Comment by Gioyik** [comment]
@lurch don't you think it's to much time for ES translation? I think, you could merge this pull request, if someone has a better translation can make other Pull Request in base of the current ES translation. It's a good solution, isn't it?

Regards,
Gio

**Comment by lurch** [comment]
Sorry, I thought you were still discussing between you who had the "best" translation...

But if you're all happy with the current translation, then I'll merge in this PR when I do the next release of NOOBS. (I wouldn't want to merge it without testing first, which I'm afraid I simply don't have time for at the moment)

**Comment by xinjia95** [comment]
Personally I think the translation is fine.

**Comment by Gioyik** [comment]
@lurch don't worry, it's ok. Take your time for the testing process.

**Comment by XECDesign** [comment]
See #373
Thank you

**Pull request closed without merging**
