### PR TITLE
Add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I add zh_TW translation, please review and merge it :smiley:

### CODE REVIEW

**Comment by s8321414** [comment]
Why not merge all of translation PR? :P

**Comment by lurch** [comment]
Lack of time for building and testing :-(

**Comment by s8321414** [comment]
Merge them all! :P XD

**Comment by NicoHood** [comment]
Yep. There is not much to test I think. Just create a branch where you merge them all and see if it works. In the PR overview you can check if only the right files were edited and if it matches. Users will complain if the translation is wrong. So I'd value the time people spend on the translation.

Or what you could also do is, to merge all PRs as I said and let the community test them and then merge.

**Comment by s8321414** [comment]
@NicoHood I prefer second way.

**Comment by XECDesign** [comment]
See #373
Thank you

**Pull request closed without merging**
